# Generated by Django 4.0.7 on 2022-11-28 14:34

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('ads', '0007_tag_rename_user_post_owner_alter_ad_tags_tag_ad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='posts',
        ),
        migrations.AlterField(
            model_name='ad',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
