# Generated by Django 4.0.7 on 2022-11-29 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_post_ad_posts_post_ad_post_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='posts',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
