# Generated by Django 4.0.7 on 2022-11-30 11:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0012_rename_user_fav_owner_alter_ad_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fav',
            old_name='owner',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='fav',
            unique_together={('ad', 'user')},
        ),
    ]
