# Generated by Django 4.0.7 on 2022-12-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_post_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='posts',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
