# Generated by Django 4.0.7 on 2022-12-05 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_alter_ad_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='tags',
        ),
    ]
